---
title: "Correlations"
output: html_document
date: "2026-01-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Davis Garden Size Correlations 

```{r}
#libraries
library(dplyr)
library(tidyverse)
library(corrplot)

sem <- function(x, na.rm=FALSE) {           #for calculating standard error
  sd(x,na.rm=na.rm)/sqrt(length(na.omit(x)))
} 
```

## Read in data 
```{r}
Biomass <- read_csv("../input/UCD_Biomass_20250723_corrected.csv")
Genotypes_2023_2024 <- read_csv("../input/Genotypes_2023_2024.csv")
UCD_annual_census_20240718_corrected <- read_csv("../input/UCD_annual_census_20240718_corrected.csv")
UCD_size_survey_20240516_corrected <- read_csv("../input/UCD_size_survey_20240516_corrected.csv")
```


```{r}
Grouped_Biomass <- Biomass %>%
group_by(unique.ID) %>%
summarize(TotalBiomass=sum(total.biomass_g), N_bags=n())
```

```{r}
#merging genotypes and biomass based on their two shared columns "unique.ID" and "blocks"
Merged_GT_BMB <- left_join(Genotypes_2023_2024, Grouped_Biomass, by = c("unique.ID"))
```

```{r}
#filtering out data before boxplot
CMerged_GT_BMB <- Merged_GT_BMB %>% 
  filter(!is.na(TotalBiomass))
```

```{r}
#box plot for correlation between population and biomass
CMerged_GT_BMB %>% 
  ggplot(aes(x=pop.id, y=TotalBiomass)) +
  geom_boxplot(width = 0.7,position = position_dodge(0.75)) + 
  facet_wrap(~ `Plant Type`, scales = "free_x") +
  theme_bw() +
  labs(x="Population", y="Biomass", title="Population vs Biomass") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/Population vs Biomass.png", width = 20, height = 14, units = "in")

#column plot for population and average biomass
CMerged_GT_BMB %>% 
  group_by(pop.id, `Plant Type`) %>% 
  summarise(mean_biomass = mean(TotalBiomass, na.rm =TRUE),
            sem_biomass = sem(TotalBiomass, na.rm =TRUE)) %>% 
  ggplot(aes(x=pop.id, y=mean_biomass)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_biomass-sem_biomass, ymax=mean_biomass+sem_biomass), #add error bars 
                width=.2, position = position_dodge(0.75)) +
  facet_wrap(~ `Plant Type`, scales = "free_x") +
  theme_bw() +
  labs(x="Population", y="Average Biomass", title="Population vs Average Biomass") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/Population vs Average Biomass.png", width = 20, height = 14, units = "in")
```

```{r}
#mutate before left joining
class(CMerged_GT_BMB$unique.ID)
class(UCD_annual_census_20240718_corrected$unique.ID)

CMerged_GT_BMB <- CMerged_GT_BMB %>%
  mutate(unique.ID = as.character(unique.ID))

UCD_annual_census_20240718_corrected <- UCD_annual_census_20240718_corrected %>%
  mutate(unique.ID = as.character(unique.ID))

```


```{r}
#merging pop/biomass with annual census
Merged_PopBio_AnCen <- left_join(CMerged_GT_BMB, UCD_annual_census_20240718_corrected)
#, by = c("unique.ID")) #don't need the by statement, R will join by all matching columns 
```


```{r}
#plot for stem diameter vs biomass
Merged_PopBio_AnCen %>% 
  ggplot(aes(x=diam.mm, y=TotalBiomass)) +
  geom_point() + 
  facet_wrap(~ `Plant Type`, scales = "free_x") +
  theme_bw() +
  labs(x="Stem Diameter (mm)", y="Biomass", title="Stem Diameter vs Biomass") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/StemDiametervsBiomass.png", width = 20, height = 8, units = "in")

#non facet plot
Merged_PopBio_AnCen %>% 
  ggplot(aes(x=diam.mm, y=TotalBiomass)) +
  geom_point() + 
  theme_bw() +
  labs(x="Stem Diameter (mm)", y="Biomass", title="Stem Diameter vs Biomass") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/StemDiamvsBiomassNonFacet.png", width = 20, height = 14, units = "in")
```

```{r}
# calculating canopy area (ellipse area formula, /2 since they are diameters)
Merged_PopBio_AnCen$canopy_area <- pi * (Merged_PopBio_AnCen$overhd.diam/2) * (Merged_PopBio_AnCen$overhd.perp/2)

```

```{r}
# graph for canopy area vs biomass (faceted)
Merged_PopBio_AnCen %>% 
  ggplot(aes(x=canopy_area, y=TotalBiomass)) +
  geom_point(width = 0.3,position = position_dodge(0.75)) + 
  facet_wrap(~ `Plant Type`, scales = "free_x") +
  theme_bw() +
  labs(x="Canopy Area", y="Biomass", title="Canopy Area vs Biomass") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/CanopyAreavsBiomass.png", width = 20, height = 8, units = "in")

#non facet plot
Merged_PopBio_AnCen %>% 
  ggplot(aes(x=canopy_area, y=TotalBiomass)) +
  geom_point(width = 0.5,position = position_dodge(0.75)) + 
  theme_bw() +
  labs(x="Canopy Area", y="Biomass", title="Canopy Area vs Biomass") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/CanopyAreavsBiomassNonFacet.png", width = 20, height = 14, units = "in")
```


```{r}
#merge size survey and biomass/pop
Merged_BioMass_Size <- left_join(CMerged_GT_BMB, UCD_size_survey_20240516_corrected)
                                 #, by = c("unique.ID")) #don't need the by statement, R will join by all matching columns 
```


```{r}
# filter out rows with no data for height and biomass columns
Merged_BioMass_Size <- Merged_BioMass_Size[!is.na(Merged_BioMass_Size$height.cm) & !is.na(Merged_BioMass_Size$TotalBiomass), ]
```


```{r}
#plot for height x biomass
Merged_BioMass_Size %>% 
  ggplot(aes(x=height.cm, y=TotalBiomass)) +
  geom_point(width = 0.3,position = position_dodge(0.75)) + 
  facet_wrap(~ `Plant Type`, scales = "free_x") +
  theme_bw() +
  labs(x="Height cm", y="Biomass", title="Height vs Biomass") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/HeightvsBiomass.png", width = 20, height = 8, units = "in")

Merged_BioMass_Size %>% 
  ggplot(aes(x=height.cm, y=TotalBiomass)) +
  geom_point(width = 0.3,position = position_dodge(0.75)) + 
  theme_bw() +
  labs(x="Height cm", y="Biomass", title="Height vs Biomass") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/HeightvsBiomassNonFacet.png", width = 20, height = 8, units = "in")
```

```{r}
# Correlation tests: Are Biomass and Height Related? Pearson corr test
cor.test(Merged_BioMass_Size$height.cm, Merged_BioMass_Size$TotalBiomass, method = "pearson")
```
```{r}
# Are Biomass and Canopy Area related?
cor.test(Merged_PopBio_AnCen$canopy_area, Merged_PopBio_AnCen$TotalBiomass, method = "pearson")
```
```{r}
# Are Biomass and Stem Diameter Related?
cor.test(Merged_PopBio_AnCen$diam.mm, Merged_PopBio_AnCen$TotalBiomass, method = "pearson")
```
```{r}
Merged_BioMass_Size$unique.ID <- as.character(Merged_BioMass_Size$unique.ID)

# left join to make size df
Merged_Size <- left_join(Merged_BioMass_Size, Merged_PopBio_AnCen)

# new df with only size variables
size_variables <- Merged_Size %>% 
  select(matches("biomass|height|area|diam.mm|width", ignore.case = TRUE))

#filter out NA values

size_variables <- size_variables%>% 
  filter(!is.na(TotalBiomass))

```


```{r}
# correlation matrix
cor_matrix <- cor(size_variables, use = "complete.obs")

png("../output/Correlation_Matrix.png", width = 800, height = 800, )
corrplot(cor_matrix,
         method = "square",
         type = "lower",
         addCoef.col = "black",
         tl.col = "black")
```
