---
title: "Rachel_Harris_IntBio"
output: html_document
date: "2025-10-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries that I'll be using + initial setup
```{r}
library(tidyverse) #includes ggplot and dplyer
library(corrplot)

sem <- function(x, na.rm=FALSE) {           #for calculating standard error
  sd(x,na.rm=na.rm)/sqrt(length(na.omit(x)))
}
```

# Load TDR Data

```{r}
combined_tdr <- read_csv("../input/WL2_2024_TDR_Processed.csv") #produced in "TDR_Plots.R"
unique(combined_tdr$date) #check for issues in date column 
#some cases of "816124"
#Where did the April time points come from? Is this an error from data entry?
combined_tdr %>% filter(Bed=="J" | Bed=="K") %>% mutate(date=mdy(date)) %>% arrange(Bed, date) #missing 9/3/24 
#some 7/2/24 and some 7/3/24, error from hand-written data - should be 7/2

combined_tdr_dates <- combined_tdr %>% 
  mutate(date=if_else(date=="816124", "8/6/24", 
                      if_else(date=="4/3/24", "9/3/24", 
                              if_else(date=="7/3/24", "7/2/24", date)))) %>%  #fix the errors found above
  mutate(date=mdy(date)) #converting the date column to a date format 
unique(combined_tdr_dates$date) #check if the date column has been properly corrected 
```

## All "over time" plots change date from character to actual dates
```{r}
#setting bed average
 bed_avg <- combined_tdr_dates %>% 
  group_by(date, Bed) %>% 
  summarize(mean_TDR = mean(TDR, na.rm = TRUE), .groups = "drop")

#Average TDR per Bed over Time Plot
 ggplot(bed_avg, aes(x = date, y = mean_TDR, color = Bed)) +
  geom_point(size = 3) +
  geom_line() +
  labs(title = "Average TDR per Bed over Time", y = "Avg TDR", x = "Date") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=25)) +
  scale_color_viridis_d(option = "viridis")
ggsave("../output/Bedovertime.png", width = 12, height = 8, units = "in")
 
#setting position average
 position_avg <- combined_tdr_dates %>% 
  group_by(date, Position) %>% 
  summarize(mean_TDR = mean(TDR, na.rm = TRUE), .groups = "drop")
 
#Average TDR per Position over Time Plot
 ggplot(position_avg, aes(x = date, y = mean_TDR, color = Position)) +
  geom_point(size = 3) +
  geom_line() +
  labs(title = "Average TDR per Position over Time", y = "Avg TDR", x = "Date") +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=25)) 
ggsave("../output/Positionovertime.png", width = 12, height = 8, units = "in")
```

## Error bars
```{r}
#Mean TDR for Each Bed
bed_means <- combined_tdr %>% 
  group_by(Bed) %>% 
  summarize(mean_TDR = mean(TDR, na.rm = TRUE),
          sem_TDR=sem(TDR, na.rm=TRUE))
bed_means

#Mean TDR per Bed
ggplot(bed_means, aes(x=fct_reorder(Bed, mean_TDR), y = mean_TDR)) +
  geom_col(fill = "steelblue") +
   geom_errorbar(aes(ymin=mean_TDR-sem_TDR,ymax=mean_TDR+sem_TDR),width=.2, position = 
                  position_dodge(0.75)) + 
  labs(title = "Mean TDR per Bed", y = "Mean TDR", x = "Bed") +
  theme_minimal() +
  theme(text=element_text(size=25)) #making the text bigger 
ggsave("../output/MeanTDRperBed.png", width = 12, height = 8, units = "in")


#new df bed_pos_means
bed_pos_means <- combined_tdr %>% 
  group_by(Position, Bed) %>% 
  summarize(mean_TDR = mean(TDR, na.rm = TRUE),
          sem_TDR=sem(TDR, na.rm=TRUE))
bed_pos_means

#Filtering plots for each bed position
bed_pos_means %>% 
  filter(Position=="top") %>% 
  ggplot(aes(x=fct_reorder(Bed, mean_TDR), y=mean_TDR)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_TDR-sem_TDR,ymax=mean_TDR+sem_TDR),width=.2, position = 
                  position_dodge(0.75)) + 
  theme_minimal() +
  theme(text=element_text(size=25)) + #making the text bigger 
  labs(x="Bed", y="Mean TDR", title="All Beds at Top Position")
ggsave("../output/MeanTDRTopBeds.png", width = 12, height = 8, units = "in")

bed_pos_means %>% 
  filter(Position=="middle") %>% 
  ggplot(aes(x=fct_reorder(Bed, mean_TDR), y=mean_TDR)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_TDR-sem_TDR,ymax=mean_TDR+sem_TDR),width=.2, position = 
                  position_dodge(0.75)) + 
  theme_minimal() +
  theme(text=element_text(size=25)) + #making the text bigger 
  labs(x="Bed", y="Mean TDR", title="All Beds at Middle Position")
ggsave("../output/MeanTDRMiddleBeds.png", width = 12, height = 8, units = "in")

bed_pos_means %>% 
  filter(Position=="end") %>% 
  ggplot(aes(x=fct_reorder(Bed, mean_TDR), y=mean_TDR)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_TDR-sem_TDR,ymax=mean_TDR+sem_TDR),width=.2, position = 
                  position_dodge(0.75)) + 
  theme_minimal() +
  theme(text=element_text(size=25)) + #making the text bigger 
  labs(x="Bed", y="Mean TDR", title="All Beds at End Position")
ggsave("../output/MeanTDREndBeds.png", width = 12, height = 8, units = "in")
```

## Compare Bed and Position over time
```{r}
#Example, A and B top
bed_pos_means %>% 
 filter(Bed %in% c("A", "B"), Position == "top") %>%  #only keep beds A and B, you could do position == "Top" for example 
  ggplot(aes(x=fct_reorder(Bed, mean_TDR), y=mean_TDR)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  geom_errorbar(aes(ymin=mean_TDR-sem_TDR,ymax=mean_TDR+sem_TDR),width=.2, position = 
                  position_dodge(0.75)) + 
  theme_classic() +
  labs(x="Bed", y="Mean TDR", title="Beds A and B at Top Position")
#ggsave("../output/MeanTDRtopBeds_AB_Time.png", width = 12, height = 8, units = "in")

bed_tdr_avg <- combined_tdr_dates %>% 
  group_by(Bed, date, Position) %>% 
  summarise(
    mean_TDR=mean(TDR, na.rm=TRUE), .groups = "drop")
bed_tdr_avg

#Average TDR of All Beds over Time - Top position 
bed_tdr_avg %>%
  filter(Position=="top") %>% 
  ggplot(aes(x =date, y =mean_TDR, color = Bed, group = Bed)) +
  geom_line(size = 1) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=25)) +
  labs(x = "Date", y = "Average TDR", color = "Bed",
    title = "Average TDR for All Beds over Time - Top") +
  scale_color_viridis_d(option = "viridis")
ggsave("../output/MeanTDRTopBed_Time.png", width = 12, height = 8, units = "in")

#Average TDR of A, K, B, C over Time - Top Position 
bed_tdr_avg %>%
  filter(Bed %in% c("A", "B", "C", "K")) %>% 
  filter(Position=="top") %>% 
  ggplot(aes(x =date, y =mean_TDR, color = Bed, group = Bed)) +
  geom_line(size = 1) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=25)) +
  labs(x = "Date", y = "Average TDR", color = "Bed",
    title = "Average TDR for Beds A, B, C K over Time- Top") +
  scale_color_viridis_d(option = "viridis")
ggsave("../output/MeanTDRTopBeds_Time.png", width = 12, height = 8, units = "in")

```

```{r}

#fixing MetStationData1
MetStationData1$X.TIMESTAMP <- sub('^"', ' ', MetStationData1$X.TIMESTAMP) #took away " at the start of every timestamp
MetStationData1$X.TIMESTAMP <- as.POSIXct(MetStationData1$X.TIMESTAMP, format="%Y-%m-%d %H:%M:%S")

MetStationData1 <- MetStationData1 %>% slice(-c(1, 2)) #removed first two empty rows

```

```{r}
#filtering metstation for dates starting in summer 2024
library(dplyr)

MetStation_summer2024 <- MetStationData1 %>% #says there is no 2024 timestamps
  filter(X.TIMESTAMP >= as.POSIXct("2024-06-01 00:00:00") &
           X.TIMESTAMP >= "2024-08-31 23:59:59")

MS_Test <- read.table("CR1000XSeries_IntBioHalfHourTable.dat", header = TRUE, sep = "", fill = TRUE)
write.csv(df, "MS_test.csv", row.names = FALSE)

```


```{r}
# correlating metstation and TDR data, example code below
wl2_cors <- wl2_establishment %>% 
  select(GrwSsn_GD_Recent, GrwSsn_GD_Historical) #make a dataframe with just the columns you want to correlate

cor.norm = cor(wl2_cors) #test correlations among the traits
cor.norm
cor.sig <- cor.mtest(wl2_cors, method = "pearson") #getting the p-values for correlations 
cor.sig
```

