---
title: "WL2 Garden Correlations"
author: "Brandie QC"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## WL2 Garden Size Correlations 
Test for relationship between stem diameter, canopy area, and height

```{r}
#libraries
library(dplyr)
library(tidyverse)
library(corrplot)
```

## Read in data 
```{r}
WL2_Annual_Census_20241023_corrected <- read_csv("../input/WL2_Annual_Census_20241023_corrected.csv")
WL2_size_survey_20240924_corrected <- read_csv("../input/WL2_size_survey_20240924_corrected.csv")
```

## Merge Data 
```{r}
## check for non-NA canopy cols 
WL2_Annual_Census_20241023_corrected %>% filter(!is.na(overhd.diam))
WL2_size_survey_20240924_corrected %>% filter(!is.na(overhd.diam))
### different rows with canopy info in the different data sheets 

## separate out canopy info from other size data 
WL2_anncens_stemdiam <- WL2_Annual_Census_20241023_corrected %>% select(bed:unique.ID, diam.mm)
WL2_anncens_canopyinfo <- WL2_Annual_Census_20241023_corrected %>% select(bed:unique.ID, overhd.diam:overhd.perp) %>% 
  filter(!is.na(overhd.diam)) #only keep columns with data 

WL2_size_height <- WL2_size_survey_20240924_corrected %>% select(bed:height.cm)
WL2_size_canopyinfo <- WL2_size_survey_20240924_corrected %>% select(bed:unique.ID, overhd.diam:overhd.perp) %>% 
  filter(!is.na(overhd.diam)) #only keep columns with data 

```

```{r}
# fixing canopy columns
WL2_anncens_canopyinfo <- WL2_anncens_canopyinfo %>% 
  mutate(DataSet = "AnnCens")

WL2_size_canopyinfo <- WL2_size_canopyinfo %>%
  mutate(DataSet = "Size")

WL2_2024_canopy <- bind_rows(WL2_anncens_canopyinfo, WL2_size_canopyinfo)

# merge 2024 data
Merged_2024 <- WL2_anncens_stemdiam %>% 
  left_join(WL2_size_height) %>% 
  left_join(WL2_2024_canopy)
Merged_2024 %>% filter(!is.na(overhd.diam)) #285 rows with canopy info, merge mostly worked
# Note that we lost 1 row of canopy info, Rachel should investigate 

Merged_2024$canopy.area <- pi * (Merged_2024$overhd.diam/2) * (Merged_2024$overhd.perp/2)
size_variables <- Merged_2024 %>% select(diam.mm:height.cm, canopy.area)
```

```{r}
# keep rows that come from anncens data
Merged_2024 <- Merged_2024 %>% 
  filter(!grepl("Size", DataSet, ignore.case = TRUE))

# remove rows without data for canopy area
Merged_2024 <- Merged_2024[!is.na(Merged_2024$canopy.area), ]
```



```{r}
# plots for correlations

# height vs canopy area
Merged_2024 %>% 
  ggplot(aes(x=height.cm, y=canopy.area)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  theme_bw() +
  labs(x="Height", y="Canopy Area", title="Height vs Canopy Area") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/Height vs Canopy.png", width = 20, height = 14, units = "in")

# overhead diameter vs canopy area
Merged_2024 %>% 
  ggplot(aes(x=overhd.diam, y=canopy.area)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  theme_bw() +
  labs(x="Diameter", y="Canopy Area", title="Overhead Diameter vs Canopy Area") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/Overhead Diameter vs Canopy Area.png", width = 20, height = 14, units = "in")

# stem diameter vs canopy area
Merged_2024 %>% 
  ggplot(aes(x=diam.mm, y=canopy.area)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  theme_bw() +
  labs(x="Stem Diameter (mm)", y="Canopy Area", title="Stem Diameter vs Canopy Area") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/Stem Diameter vs Canopy Area.png", width = 20, height = 14, units = "in")

# overhead perp vs canopy area
Merged_2024 %>% 
  ggplot(aes(x=overhd.perp, y=canopy.area)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  theme_bw() +
  labs(x="Perpendicular", y="Canopy Area", title="Overhead Perpendicular vs Canopy Area") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/Perpendicular vs Canopy Area.png", width = 20, height = 14, units = "in")
```


```{r}
# 2024 correlation matrix
cor_matrix <- cor(size_variables, use = "complete.obs")

png("../output/WL2_2024_Correlation_Matrix.png", width = 800, height = 800, )
corrplot(cor_matrix,
         method = "square",
         type = "lower",
         addCoef.col = "black",
         tl.col = "black")
```


```{r}
# Read in 2025 data
WL2_ann_cens_20251028_corrected <- read.csv("../input/WL2_ann_cens_20251006_corrected.csv")
WL2_size_survey_20250924_blocksA_F_corrected <- read.csv("../input/WL2_size_survey_20250924_blocksA-F_corrected.csv")
WL2_size_survey_20250929_blocksG_N_corrected <- read.csv("../input/WL2_size_survey_20250929_blocksG-N_corrected.csv")
```

```{r}
# filter + merge 2025 data
WL2_ann_cens_20251028_corrected %>% filter(!is.na(diam.mm))
WL2_size_survey_20250924_blocksA_F_corrected %>% filter(!is.na(overhd.diam))
WL2_size_survey_20250929_blocksG_N_corrected %>%  filter(!is.na(overhd.diam))

# get only canopy information
WL2_20251028_stemdiam <- WL2_ann_cens_20251028_corrected %>% select(bed:Unique.ID, diam.mm)
WL2_20250924A_F_canopyinfo <- WL2_size_survey_20250924_blocksA_F_corrected %>% select(bed:Unique.ID, overhd.diam:overhd.perp, height.cm) %>% 
  filter(!is.na(overhd.diam))
WL2_20250929G_N_canopyinfo <- WL2_size_survey_20250929_blocksG_N_corrected %>% select(bed:Unique.ID, overhd.diam:overhd.perp, height.cm) %>% 
  filter(!is.na(overhd.diam))
```
```{r}
# bind rows for size surveys
size_survey_2025 <- bind_rows(WL2_size_survey_20250924_blocksA_F_corrected, WL2_size_survey_20250929_blocksG_N_corrected)

# mark rows from each dataset to keep track in Merged_2025
size_survey_2025 <- size_survey_2025 %>%
  mutate(DataSet = "Size")

WL2_ann_cens_20251028_corrected <- WL2_ann_cens_20251028_corrected %>%
  mutate(DataSet = "AnnCens")

```


```{r}
# chunk to debug merged_2025 
Merged_2025 %>% 
  count(is.na(overhd.diam))

unmatched <- anti_join(
  size_survey_2025, 
  WL2_ann_cens_20251028_corrected, 
  by = "row"
)

head(unmatched$row)

names(size_survey_2025)
names(WL2_ann_cens_20251028_corrected)
```
```{r}
# debugging chunk for size_survey_2025
size_survey_2025 <- size_survey_2025 %>%
  mutate(
    survey.date = mdy(survey.date)
)

size_latest <- size_clean %>%
  group_by(Unique.ID) %>%
  slice_max(order_by = survey.date, n = 1, with_ties = FALSE) %>%
  ungroup()

size_latest %>%
  count(Unique.ID) %>%
  filter(n > 1)

```



```{r}
# merge 2025 data + filter
Merged_2025 <- size_survey_2025 %>% 
  left_join(
    WL2_ann_cens_20251028_corrected %>%
      select(bed, row, col, diam.mm),
    by = c("bed", "row", "col")
  )

# LEFT OFF HERE 4/14/26
```

```{r} 
# code to keep/replace later
Merged_2025 <- WL2_ann_cens_20251028_corrected %>% 
  left_join(
    size_survey_2025 %>% 
      select(Unique.ID, height.cm, overhd.diam, overhd.perp ),
    by = "Unique.ID")
```



```{r}
# plots for 2025 correlations

# height vs canopy area
Merged_2025 %>% 
  ggplot(aes(x=height.cm, y=canopy.area)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  theme_bw() +
  labs(x="Height", y="Canopy Area", title="Height vs Canopy Area") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/Height_v_Canopy_2025.png", width = 20, height = 14, units = "in")

# overhead perp vs canopy area
Merged_2025 %>% 
  ggplot(aes(x=overhd.perp, y=canopy.area)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  theme_bw() +
  labs(x="Overhead Perpendicular", y="Canopy Area", title="Overhead Perpendicular vs Canopy Area") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/Perpendicular_v_CanopyArea_2025.png", width = 20, height = 14, units = "in")

# Overhead diameter vs canopy area
Merged_2025 %>% 
  ggplot(aes(x=overhd.diam, y=canopy.area)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  theme_bw() +
  labs(x="Diameter", y="Canopy Area", title="Diameter vs Canopy Area") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/Diameter_v_CanopyArea_2025.png", width = 20, height = 14, units = "in")

# stem diameter vs canopy area
Merged_2025 %>% 
  ggplot(aes(x=diam.mm, y=canopy.area)) +
  geom_col(width = 0.7,position = position_dodge(0.75)) + 
  theme_bw() +
  labs(x="Stem Diameter", y="Canopy Area", title="Stem Diameter vs Canopy Area") + 
  theme(axis.text.x = element_text(angle = 45, hjust =1, size = 11), text=element_text(size=20))
ggsave("../output/Stem_v_CanopyArea_2025.png", width = 20, height = 14, units = "in")
# NOTE: stem diameter graph had limited data to work with, not many rows with diam.mm data
```

```{r}
# 2025 correlation matrix
cor_matrix_2025 <- cor(size_variables_2025, use = "complete.obs")

png("../output/WL2_2025_Correlation_Matrix.png", width = 800, height = 800, )
corrplot(cor_matrix,
         method = "square",
         type = "lower",
         addCoef.col = "black",
         tl.col = "black")
```

```{r}
sum(!is.na(WL2_ann_cens_20251006_corrected$diam.mm))
```

